import { useMemo } from 'react';
import { useStore } from '../../../store';
import {
  startOfDay, differenceInHours, differenceInCalendarDays,
  parseISO, isValid, format, subDays, startOfMonth, endOfMonth,
  eachWeekOfInterval, startOfWeek, endOfWeek, endOfDay
} from 'date-fns';
import { getDescendantIds } from '../../assets/utils/assetHelpers';

export type Period = '7d' | '30d' | '90d' | 'month' | 'custom';

function safeParse(d: string | null | undefined): Date | null {
  if (!d) return null;
  const p = parseISO(d);
  return isValid(p) ? p : null;
}

function periodRange(period: Period, custom?: { from: string; to: string }): { from: Date; to: Date } {
  const today = startOfDay(new Date());
  const nowEnd = endOfDay(new Date());
  
  if (period === '7d')    return { from: subDays(today, 6), to: nowEnd };
  if (period === '30d')   return { from: subDays(today, 29), to: nowEnd };
  if (period === '90d')   return { from: subDays(today, 89), to: nowEnd };
  if (period === 'month') return { from: startOfMonth(today), to: endOfMonth(today) };
  if (period === 'custom' && custom) {
    const cFrom = safeParse(custom.from);
    const cTo = safeParse(custom.to);
    if (cFrom && cTo) {
      const fromD = startOfDay(cFrom);
      const toD = endOfDay(cTo);
      return fromD <= toD ? { from: fromD, to: toD } : { from: startOfDay(cTo), to: endOfDay(cFrom) };
    }
  }
  return { from: subDays(today, 29), to: nowEnd };
}

export function useKpiData(
  period: Period,
  custom?: { from: string; to: string },
  filterPlant?: string,
  filterArea?: string,
) {
  const store = useStore() as any;
  const { workOrders = [], assetPlans = [], pmPlans = [], inventoryItems = [], assets = [], users = [] } = store;

  const range = useMemo(() => periodRange(period, custom), [period, custom]);

  // Filtered asset ids based on plant/area selection
  const filteredAssetIds = useMemo(() => {
    if (!filterPlant && !filterArea) return null; // null = no filter
    const rootId = filterArea || filterPlant;
    if (!rootId) return null;
    
    // Get root + all descendants
    const subtreeIds = new Set(getDescendantIds(rootId, assets));
    subtreeIds.add(rootId);
    return subtreeIds;
  }, [assets, filterPlant, filterArea]);

  // Filter WOs within period (use createdAt as anchor)
  const periodWos = useMemo(() =>
    workOrders.filter((w: any) => {
      const d = safeParse(w.createdAt);
      if (!d || d < range.from || d > range.to) return false;
      if (filteredAssetIds && !filteredAssetIds.has(w.assetId)) return false;
      return true;
    }), [workOrders, range, filteredAssetIds]);

  const completedWos = useMemo(() =>
    periodWos.filter((w: any) => w.status === 'completed'), [periodWos]);

  const overdueWos = useMemo(() => {
    const today = new Date();
    return workOrders.filter((w: any) => {
      if (['completed', 'cancelled'].includes(w.status)) return false;
      const due = safeParse(w.dueDate);
      if (!due || due >= today) return false;
      if (filteredAssetIds && !filteredAssetIds.has(w.assetId)) return false;
      return true;
    });
  }, [workOrders, filteredAssetIds]);

  // ── OVERVIEW KPIs ────────────────────────────────────────────
  const overview = useMemo(() => {
    const total = periodWos.length;
    const completed = completedWos.length;
    const correctives = periodWos.filter((w: any) => w.woType === 'corrective');
    const preventives = periodWos.filter((w: any) => w.woType === 'preventive');

    // MTTR — mean actual hours on completed WOs with hours data
    const wosWithHours = completedWos.filter((w: any) => w.actualHours != null && w.actualHours > 0);
    const mttr = wosWithHours.length > 0
      ? wosWithHours.reduce((s: number, w: any) => s + w.actualHours, 0) / wosWithHours.length
      : 0;

    // Compliance PM: preventive WOs completed vs total WOs generated by PM engine
    const pmGenerated = periodWos.filter((w: any) => w.assetPlanId != null).length;
    const pmCompleted = completedWos.filter((w: any) => w.assetPlanId != null).length;
    const pmCompliance = pmGenerated > 0 ? Math.round((pmCompleted / pmGenerated) * 100) : 0;

    // WOs completed on time
    const onTime = completedWos.filter((w: any) => {
      if (!w.dueDate || !w.completedAt) return false;
      return parseISO(w.completedAt) <= parseISO(w.dueDate);
    }).length;
    const slaCompliance = completed > 0 ? Math.round((onTime / completed) * 100) : 0;

    // Costs
    const externalCost = completedWos.reduce((s: number, w: any) => s + (w.externalServiceCost || 0), 0);

    // MTBF (time between corrective failures on SAME asset)
    const correctivesByAsset: Record<string, Date[]> = {};
    correctives.forEach((w: any) => {
      const d = safeParse(w.createdAt);
      if (d) {
        if (!correctivesByAsset[w.assetId]) correctivesByAsset[w.assetId] = [];
        correctivesByAsset[w.assetId].push(d);
      }
    });

    let totalGapsHours = 0;
    let gapCount = 0;

    Object.values(correctivesByAsset).forEach(dates => {
      if (dates.length > 1) {
        dates.sort((a, b) => a.getTime() - b.getTime());
        for (let i = 1; i < dates.length; i++) {
          totalGapsHours += differenceInHours(dates[i], dates[i - 1]);
          gapCount++;
        }
      }
    });

    const mtbf = gapCount > 0 ? Math.round(totalGapsHours / gapCount) : 0;

    const stockCritical = inventoryItems.filter((i: any) => i.stockCurrent <= i.stockMin && i.active).length;

    return {
      total, completed, correctives: correctives.length, preventives: preventives.length,
      mttr: Math.round(mttr * 10) / 10,
      mtbf,
      pmCompliance, slaCompliance,
      externalCost, stockCritical,
      overdueCount: overdueWos.length,
    };
  }, [periodWos, completedWos, overdueWos, inventoryItems]);

  // ── WO DISTRIBUTION by week ──────────────────────────────────
  const woByWeek = useMemo(() => {
    const weeks = eachWeekOfInterval({ start: range.from, end: range.to }, { weekStartsOn: 1 });
    return weeks.map(weekStart => {
      const weekEnd = endOfWeek(weekStart, { weekStartsOn: 1 });
      const label = format(weekStart, 'dd MMM');
      const wos = periodWos.filter((w: any) => {
        const d = safeParse(w.createdAt);
        return d && d >= startOfWeek(weekStart, { weekStartsOn: 1 }) && d <= weekEnd;
      });
      return {
        label,
        preventive: wos.filter((w: any) => w.woType === 'preventive').length,
        corrective: wos.filter((w: any) => w.woType === 'corrective').length,
        predictive: wos.filter((w: any) => w.woType === 'predictive').length,
        inspection: wos.filter((w: any) => w.woType === 'inspection').length,
      };
    });
  }, [periodWos, range]);

  // ── WO TYPE DONUT ─────────────────────────────────────────────
  const woTypeDonut = useMemo(() => {
    const types = ['preventive', 'corrective', 'predictive', 'inspection'];
    return types.map(t => ({
      name: { preventive: 'Preventiva', corrective: 'Correctiva', predictive: 'Predictiva', inspection: 'Inspección' }[t],
      value: periodWos.filter((w: any) => w.woType === t).length,
      color: { preventive: '#3b82f6', corrective: '#f59e0b', predictive: '#a855f7', inspection: '#10b981' }[t],
    })).filter(t => t.value > 0);
  }, [periodWos]);

  // ── WO STATUS DONUT ───────────────────────────────────────────
  const woStatusDonut = useMemo(() => {
    const statuses = ['open', 'assigned', 'in_progress', 'on_hold', 'completed', 'cancelled'];
    return statuses.map(s => ({
      name: { open: 'Abierta', assigned: 'Asignada', in_progress: 'En Progreso', on_hold: 'En Espera', completed: 'Completada', cancelled: 'Cancelada' }[s],
      value: periodWos.filter((w: any) => w.status === s).length,
      color: { open: '#94a3b8', assigned: '#3b82f6', in_progress: '#f59e0b', on_hold: '#8b5cf6', completed: '#10b981', cancelled: '#ef4444' }[s],
    })).filter(s => s.value > 0);
  }, [periodWos]);

  // ── PM COMPLIANCE per plan ────────────────────────────────────
  const pmComplianceByPlan = useMemo(() => {
    return assetPlans
      .filter((ap: any) => {
        if (!ap.active) return false;
        if (filteredAssetIds && !filteredAssetIds.has(ap.assetId)) return false;
        return true;
      })
      .map((ap: any) => {
        const plan = pmPlans.find((p: any) => p.id === ap.pmPlanId);
        const asset = assets.find((a: any) => a.id === ap.assetId);
        
        // Only WOs for this plan created within the period
        const wosInPeriod = workOrders.filter((w: any) => {
          if (w.assetPlanId !== ap.id) return false;
          const d = safeParse(w.createdAt);
          return d && d >= range.from && d <= range.to;
        });
        
        const completedInPeriod = wosInPeriod.filter((w: any) => w.status === 'completed').length;
        
        const today = new Date();
        const due = safeParse(ap.nextDueDate);
        const daysUntilDue = due ? differenceInCalendarDays(due, today) : null;
        let state: 'ok' | 'soon' | 'overdue' = 'ok';
        if (daysUntilDue !== null) {
          if (daysUntilDue < 0) state = 'overdue';
          else if (daysUntilDue <= 7) state = 'soon';
        }
        return {
          id: ap.id,
          planName: plan?.name || ap.pmPlanId,
          assetName: asset?.name || ap.assetId,
          cycleIndex: ap.currentCycleIndex,
          nextDueDate: ap.nextDueDate,
          daysUntilDue,
          completedInPeriod,
          totalWos: wosInPeriod.length,
          state,
        };
      })
      .sort((a: any, b: any) => {
        const stateOrder: Record<string, number> = { overdue: 0, soon: 1, ok: 2 };
        return (stateOrder[a.state] ?? 3) - (stateOrder[b.state] ?? 3);
      });
  }, [assetPlans, pmPlans, assets, workOrders, range]);

  // ── COST by TYPE (bar) ────────────────────────────────────────
  const costByType = useMemo(() => {
    const types = ['preventive', 'corrective', 'predictive', 'inspection'];
    return types.map(t => ({
      name: { preventive: 'Preventiva', corrective: 'Correctiva', predictive: 'Predictiva', inspection: 'Inspección' }[t],
      cost: completedWos
        .filter((w: any) => w.woType === t)
        .reduce((s: number, w: any) => s + (w.externalServiceCost || 0), 0),
      color: { preventive: '#3b82f6', corrective: '#f59e0b', predictive: '#a855f7', inspection: '#10b981' }[t],
    })).filter(t => t.cost > 0);
  }, [completedWos]);

  // ── TOP ASSETS by WO count ─────────────────────────────────────
  const topAssetsByWo = useMemo(() => {
    const map: Record<string, { name: string; count: number; cost: number }> = {};
    periodWos.forEach((w: any) => {
      const id = w.assetId;
      if (!map[id]) map[id] = { name: w.assetNameSnapshot || id, count: 0, cost: 0 };
      map[id].count++;
      map[id].cost += w.externalServiceCost || 0;
    });
    return Object.values(map).sort((a, b) => b.count - a.count).slice(0, 8);
  }, [periodWos]);

  // ── TECHNICIAN performance ─────────────────────────────────────
  const techPerformance = useMemo(() => {
    const map: Record<string, { name: string; assigned: number; completed: number; totalHours: number }> = {};
    periodWos.forEach((w: any) => {
      const id = w.assignedTo || 'unassigned';
      const name = w.assignedToNameSnapshot || (id === 'unassigned' ? 'Sin asignar' : id);
      if (!map[id]) map[id] = { name, assigned: 0, completed: 0, totalHours: 0 };
      map[id].assigned++;
      if (w.status === 'completed') {
        map[id].completed++;
        map[id].totalHours += w.actualHours || 0;
      }
    });
    return Object.values(map)
      .sort((a, b) => b.assigned - a.assigned)
      .slice(0, 8)
      .map(t => ({ ...t, efficiency: t.assigned > 0 ? Math.round((t.completed / t.assigned) * 100) : 0 }));
  }, [periodWos]);

  // ── INVENTORY KPIs ────────────────────────────────────────────
  const inventoryKpis = useMemo(() => {
    const active = inventoryItems.filter((i: any) => i.active);
    const belowMin = active.filter((i: any) => i.stockCurrent <= i.stockMin);
    const totalValue = active.reduce((s: number, i: any) => s + (i.stockCurrent * (i.unitCost || 0)), 0);
    return { total: active.length, belowMin: belowMin.length, totalValue, belowMinItems: belowMin };
  }, [inventoryItems]);

  return {
    range,
    overview,
    woByWeek,
    woTypeDonut,
    woStatusDonut,
    pmComplianceByPlan,
    costByType,
    topAssetsByWo,
    techPerformance,
    inventoryKpis,
    overdueWos,
    periodWos,
    completedWos,
    assets,
    users,
  };
}
